### ISSUE TITLE
mm2.properties file does not exist in /tmp/kafka/config/mm2.properties and cannot be put there

### ISSUE THREAD

**Issue by douglasawh** [mroiter-larus/kafka-docker-mm2#1]
Step 4 at https://medium.com/larus-team/how-to-setup-mirrormaker-2-0-on-apache-kafka-multi-cluster-environment-87712d7997a4 says the config file should be there. I bet I can just put that config file somewhere where appuser has access, but I don't know what is supposed to go in there.

[appuser@mirror-maker ~]$ cd /tmp/kafka/config
[appuser@mirror-maker config]$ ls -la
total 0
drwxr-xr-x. 2 root root  6 Feb  3 22:32 .
drwxr-xr-x. 3 root root 20 Feb  3 22:32 ..
[appuser@mirror-maker config]$ touch file
touch: cannot touch 'file': Permission denied

**Comment by douglasawh** [comment]
the mm2.properties content is earlier in the post, but there's no file editor as far as I can tell (vim, vi, nano, pico)

**Comment by mroiter-larus** [comment]
Hi @douglasawh,

i've tested it locally and the file `mm2.properties` is exactly where it is supposed to be. Following a screenshot:

<img width="1465" alt="Screenshot 2022-02-07 at 12 25 11" src="https://user-images.githubusercontent.com/12952543/152779861-4e1ee8d8-0aa7-40bd-9155-99899bcfb881.png">

As you can see into the `docker-compose.yml`, there's a volume defined for the `mirror-maker` container:

```
  mirror-maker:
    image: confluentinc/cp-kafka
    hostname: mirror-maker
    container_name: mirror-maker
    volumes:
      - ./mm2_config:/tmp/kafka/config
```

You just need a folder called `mm2_config` which contains the `mm2.properties` file, at the same level where the `docker-compose.yml` file exists. If you clone this Git repo you'll have all you need, and you'll just need to follow the steps described in the article.

Hope this helps.

**Comment by douglasawh** [comment]
Hmm, I did clone the repo. Perhaps the clone did not complete properly. I will check later. Thanks!

**Comment by mroiter-larus** [comment]
Hi @douglasawh,

any news?

**Comment by douglasawh** [comment]
@mroiter-larus thanks for the follow-up! I'm still working through some MirrorMaker issues, but I don't think they are related to the guide.

For anyone curious, what happened here is that I had the docker-compose.yml in two different directories. I was using one in the wrong place.
