### ISSUE TITLE
Topics with the same name in source and target cluster

### ISSUE THREAD

**Issue by MojtabaShayegh** [mroiter-larus/kafka-docker-mm2#4]
Hi,
When I use this method to replicate my topics, the target cluster has a topic with `source.` in the front of the topic name. How could I have the exact same name in both clusters?

**Comment by mroiter-larus** [comment]
Hi @MojtabaShayegh,

have you already tried to change the default replication policy? You would have to change the `replication.policy.class` parameter in the Mirror Maker configuration.

```
replication.policy.class=org.apache.kafka.connect.mirror.IdentityReplicationPolicy
```

As per the Apache documentation:

```
The Connect-based MirrorMaker (MM2) includes changes to support IdentityReplicationPolicy, enabling 
replication without renaming topics. 
The existing `DefaultReplicationPolicy` is still used by default, but identity replication can be enabled 
via the replication.policy configuration property. 
This is especially useful for users migrating from the older MirrorMaker (MM1), or for use-cases with 
simple one-way replication topologies where topic renaming is undesirable. Note that 
`IdentityReplicationPolicy`, unlike `DefaultReplicationPolicy`, cannot prevent replication cycles based on 
topic names, so take care to avoid cycles when constructing your replication topology.
```

You can also define your own custom replication policy. For further details checkout the documentation at the following link: https://kafka.apache.org/documentation/#georeplication-topic-naming

Hope this helps

**Comment by MojtabaShayegh** [comment]
Hi,
Yes, it worked
Thanx
